apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    role: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      role: helloworld
      tier: web
  template:
    metadata:
      labels:
        role: helloworld
        tier: web
    spec:
      containers:
      - name: helloworld-app
        image: davidcheong/java-helloworld
        ports:
        - containerPort: 8080
